/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSindicoRouteImport } from './routes/_authenticated/sindico'
import { Route as AuthenticatedPendenteRouteImport } from './routes/_authenticated/pendente'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMoradorRouteImport } from './routes/_authenticated/morador'
import { Route as AuthenticatedSindicoReservasRouteImport } from './routes/_authenticated/sindico/reservas'
import { Route as AuthenticatedSindicoOnboardingRouteImport } from './routes/_authenticated/sindico/onboarding'
import { Route as AuthenticatedSindicoMoradoresRouteImport } from './routes/_authenticated/sindico/moradores'
import { Route as AuthenticatedSindicoFinanceiroRouteImport } from './routes/_authenticated/sindico/financeiro'
import { Route as AuthenticatedSindicoEnergiaRouteImport } from './routes/_authenticated/sindico/energia'
import { Route as AuthenticatedSindicoDashboardRouteImport } from './routes/_authenticated/sindico/dashboard'
import { Route as AuthenticatedSindicoConfiguracoesRouteImport } from './routes/_authenticated/sindico/configuracoes'
import { Route as AuthenticatedSindicoComplianceRouteImport } from './routes/_authenticated/sindico/compliance'
import { Route as AuthenticatedSindicoCarregadoresRouteImport } from './routes/_authenticated/sindico/carregadores'
import { Route as AuthenticatedMoradorReservasRouteImport } from './routes/_authenticated/morador/reservas'
import { Route as AuthenticatedMoradorReservarRouteImport } from './routes/_authenticated/morador/reservar'
import { Route as AuthenticatedMoradorPerfilRouteImport } from './routes/_authenticated/morador/perfil'
import { Route as AuthenticatedMoradorHomeRouteImport } from './routes/_authenticated/morador/home'
import { Route as AuthenticatedMoradorFilaRouteImport } from './routes/_authenticated/morador/fila'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSindicoRoute = AuthenticatedSindicoRouteImport.update({
  id: '/sindico',
  path: '/sindico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendenteRoute = AuthenticatedPendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMoradorRoute = AuthenticatedMoradorRouteImport.update({
  id: '/morador',
  path: '/morador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSindicoReservasRoute =
  AuthenticatedSindicoReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoOnboardingRoute =
  AuthenticatedSindicoOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoMoradoresRoute =
  AuthenticatedSindicoMoradoresRouteImport.update({
    id: '/moradores',
    path: '/moradores',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoFinanceiroRoute =
  AuthenticatedSindicoFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoEnergiaRoute =
  AuthenticatedSindicoEnergiaRouteImport.update({
    id: '/energia',
    path: '/energia',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoDashboardRoute =
  AuthenticatedSindicoDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoConfiguracoesRoute =
  AuthenticatedSindicoConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoComplianceRoute =
  AuthenticatedSindicoComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedSindicoCarregadoresRoute =
  AuthenticatedSindicoCarregadoresRouteImport.update({
    id: '/carregadores',
    path: '/carregadores',
    getParentRoute: () => AuthenticatedSindicoRoute,
  } as any)
const AuthenticatedMoradorReservasRoute =
  AuthenticatedMoradorReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedMoradorRoute,
  } as any)
const AuthenticatedMoradorReservarRoute =
  AuthenticatedMoradorReservarRouteImport.update({
    id: '/reservar',
    path: '/reservar',
    getParentRoute: () => AuthenticatedMoradorRoute,
  } as any)
const AuthenticatedMoradorPerfilRoute =
  AuthenticatedMoradorPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedMoradorRoute,
  } as any)
const AuthenticatedMoradorHomeRoute =
  AuthenticatedMoradorHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedMoradorRoute,
  } as any)
const AuthenticatedMoradorFilaRoute =
  AuthenticatedMoradorFilaRouteImport.update({
    id: '/fila',
    path: '/fila',
    getParentRoute: () => AuthenticatedMoradorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/morador': typeof AuthenticatedMoradorRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendente': typeof AuthenticatedPendenteRoute
  '/sindico': typeof AuthenticatedSindicoRouteWithChildren
  '/morador/fila': typeof AuthenticatedMoradorFilaRoute
  '/morador/home': typeof AuthenticatedMoradorHomeRoute
  '/morador/perfil': typeof AuthenticatedMoradorPerfilRoute
  '/morador/reservar': typeof AuthenticatedMoradorReservarRoute
  '/morador/reservas': typeof AuthenticatedMoradorReservasRoute
  '/sindico/carregadores': typeof AuthenticatedSindicoCarregadoresRoute
  '/sindico/compliance': typeof AuthenticatedSindicoComplianceRoute
  '/sindico/configuracoes': typeof AuthenticatedSindicoConfiguracoesRoute
  '/sindico/dashboard': typeof AuthenticatedSindicoDashboardRoute
  '/sindico/energia': typeof AuthenticatedSindicoEnergiaRoute
  '/sindico/financeiro': typeof AuthenticatedSindicoFinanceiroRoute
  '/sindico/moradores': typeof AuthenticatedSindicoMoradoresRoute
  '/sindico/onboarding': typeof AuthenticatedSindicoOnboardingRoute
  '/sindico/reservas': typeof AuthenticatedSindicoReservasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/morador': typeof AuthenticatedMoradorRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendente': typeof AuthenticatedPendenteRoute
  '/sindico': typeof AuthenticatedSindicoRouteWithChildren
  '/morador/fila': typeof AuthenticatedMoradorFilaRoute
  '/morador/home': typeof AuthenticatedMoradorHomeRoute
  '/morador/perfil': typeof AuthenticatedMoradorPerfilRoute
  '/morador/reservar': typeof AuthenticatedMoradorReservarRoute
  '/morador/reservas': typeof AuthenticatedMoradorReservasRoute
  '/sindico/carregadores': typeof AuthenticatedSindicoCarregadoresRoute
  '/sindico/compliance': typeof AuthenticatedSindicoComplianceRoute
  '/sindico/configuracoes': typeof AuthenticatedSindicoConfiguracoesRoute
  '/sindico/dashboard': typeof AuthenticatedSindicoDashboardRoute
  '/sindico/energia': typeof AuthenticatedSindicoEnergiaRoute
  '/sindico/financeiro': typeof AuthenticatedSindicoFinanceiroRoute
  '/sindico/moradores': typeof AuthenticatedSindicoMoradoresRoute
  '/sindico/onboarding': typeof AuthenticatedSindicoOnboardingRoute
  '/sindico/reservas': typeof AuthenticatedSindicoReservasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/morador': typeof AuthenticatedMoradorRouteWithChildren
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pendente': typeof AuthenticatedPendenteRoute
  '/_authenticated/sindico': typeof AuthenticatedSindicoRouteWithChildren
  '/_authenticated/morador/fila': typeof AuthenticatedMoradorFilaRoute
  '/_authenticated/morador/home': typeof AuthenticatedMoradorHomeRoute
  '/_authenticated/morador/perfil': typeof AuthenticatedMoradorPerfilRoute
  '/_authenticated/morador/reservar': typeof AuthenticatedMoradorReservarRoute
  '/_authenticated/morador/reservas': typeof AuthenticatedMoradorReservasRoute
  '/_authenticated/sindico/carregadores': typeof AuthenticatedSindicoCarregadoresRoute
  '/_authenticated/sindico/compliance': typeof AuthenticatedSindicoComplianceRoute
  '/_authenticated/sindico/configuracoes': typeof AuthenticatedSindicoConfiguracoesRoute
  '/_authenticated/sindico/dashboard': typeof AuthenticatedSindicoDashboardRoute
  '/_authenticated/sindico/energia': typeof AuthenticatedSindicoEnergiaRoute
  '/_authenticated/sindico/financeiro': typeof AuthenticatedSindicoFinanceiroRoute
  '/_authenticated/sindico/moradores': typeof AuthenticatedSindicoMoradoresRoute
  '/_authenticated/sindico/onboarding': typeof AuthenticatedSindicoOnboardingRoute
  '/_authenticated/sindico/reservas': typeof AuthenticatedSindicoReservasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/morador'
    | '/notificacoes'
    | '/pendente'
    | '/sindico'
    | '/morador/fila'
    | '/morador/home'
    | '/morador/perfil'
    | '/morador/reservar'
    | '/morador/reservas'
    | '/sindico/carregadores'
    | '/sindico/compliance'
    | '/sindico/configuracoes'
    | '/sindico/dashboard'
    | '/sindico/energia'
    | '/sindico/financeiro'
    | '/sindico/moradores'
    | '/sindico/onboarding'
    | '/sindico/reservas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/morador'
    | '/notificacoes'
    | '/pendente'
    | '/sindico'
    | '/morador/fila'
    | '/morador/home'
    | '/morador/perfil'
    | '/morador/reservar'
    | '/morador/reservas'
    | '/sindico/carregadores'
    | '/sindico/compliance'
    | '/sindico/configuracoes'
    | '/sindico/dashboard'
    | '/sindico/energia'
    | '/sindico/financeiro'
    | '/sindico/moradores'
    | '/sindico/onboarding'
    | '/sindico/reservas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/morador'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pendente'
    | '/_authenticated/sindico'
    | '/_authenticated/morador/fila'
    | '/_authenticated/morador/home'
    | '/_authenticated/morador/perfil'
    | '/_authenticated/morador/reservar'
    | '/_authenticated/morador/reservas'
    | '/_authenticated/sindico/carregadores'
    | '/_authenticated/sindico/compliance'
    | '/_authenticated/sindico/configuracoes'
    | '/_authenticated/sindico/dashboard'
    | '/_authenticated/sindico/energia'
    | '/_authenticated/sindico/financeiro'
    | '/_authenticated/sindico/moradores'
    | '/_authenticated/sindico/onboarding'
    | '/_authenticated/sindico/reservas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sindico': {
      id: '/_authenticated/sindico'
      path: '/sindico'
      fullPath: '/sindico'
      preLoaderRoute: typeof AuthenticatedSindicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pendente': {
      id: '/_authenticated/pendente'
      path: '/pendente'
      fullPath: '/pendente'
      preLoaderRoute: typeof AuthenticatedPendenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/morador': {
      id: '/_authenticated/morador'
      path: '/morador'
      fullPath: '/morador'
      preLoaderRoute: typeof AuthenticatedMoradorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sindico/reservas': {
      id: '/_authenticated/sindico/reservas'
      path: '/reservas'
      fullPath: '/sindico/reservas'
      preLoaderRoute: typeof AuthenticatedSindicoReservasRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/onboarding': {
      id: '/_authenticated/sindico/onboarding'
      path: '/onboarding'
      fullPath: '/sindico/onboarding'
      preLoaderRoute: typeof AuthenticatedSindicoOnboardingRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/moradores': {
      id: '/_authenticated/sindico/moradores'
      path: '/moradores'
      fullPath: '/sindico/moradores'
      preLoaderRoute: typeof AuthenticatedSindicoMoradoresRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/financeiro': {
      id: '/_authenticated/sindico/financeiro'
      path: '/financeiro'
      fullPath: '/sindico/financeiro'
      preLoaderRoute: typeof AuthenticatedSindicoFinanceiroRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/energia': {
      id: '/_authenticated/sindico/energia'
      path: '/energia'
      fullPath: '/sindico/energia'
      preLoaderRoute: typeof AuthenticatedSindicoEnergiaRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/dashboard': {
      id: '/_authenticated/sindico/dashboard'
      path: '/dashboard'
      fullPath: '/sindico/dashboard'
      preLoaderRoute: typeof AuthenticatedSindicoDashboardRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/configuracoes': {
      id: '/_authenticated/sindico/configuracoes'
      path: '/configuracoes'
      fullPath: '/sindico/configuracoes'
      preLoaderRoute: typeof AuthenticatedSindicoConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/compliance': {
      id: '/_authenticated/sindico/compliance'
      path: '/compliance'
      fullPath: '/sindico/compliance'
      preLoaderRoute: typeof AuthenticatedSindicoComplianceRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/sindico/carregadores': {
      id: '/_authenticated/sindico/carregadores'
      path: '/carregadores'
      fullPath: '/sindico/carregadores'
      preLoaderRoute: typeof AuthenticatedSindicoCarregadoresRouteImport
      parentRoute: typeof AuthenticatedSindicoRoute
    }
    '/_authenticated/morador/reservas': {
      id: '/_authenticated/morador/reservas'
      path: '/reservas'
      fullPath: '/morador/reservas'
      preLoaderRoute: typeof AuthenticatedMoradorReservasRouteImport
      parentRoute: typeof AuthenticatedMoradorRoute
    }
    '/_authenticated/morador/reservar': {
      id: '/_authenticated/morador/reservar'
      path: '/reservar'
      fullPath: '/morador/reservar'
      preLoaderRoute: typeof AuthenticatedMoradorReservarRouteImport
      parentRoute: typeof AuthenticatedMoradorRoute
    }
    '/_authenticated/morador/perfil': {
      id: '/_authenticated/morador/perfil'
      path: '/perfil'
      fullPath: '/morador/perfil'
      preLoaderRoute: typeof AuthenticatedMoradorPerfilRouteImport
      parentRoute: typeof AuthenticatedMoradorRoute
    }
    '/_authenticated/morador/home': {
      id: '/_authenticated/morador/home'
      path: '/home'
      fullPath: '/morador/home'
      preLoaderRoute: typeof AuthenticatedMoradorHomeRouteImport
      parentRoute: typeof AuthenticatedMoradorRoute
    }
    '/_authenticated/morador/fila': {
      id: '/_authenticated/morador/fila'
      path: '/fila'
      fullPath: '/morador/fila'
      preLoaderRoute: typeof AuthenticatedMoradorFilaRouteImport
      parentRoute: typeof AuthenticatedMoradorRoute
    }
  }
}

interface AuthenticatedMoradorRouteChildren {
  AuthenticatedMoradorFilaRoute: typeof AuthenticatedMoradorFilaRoute
  AuthenticatedMoradorHomeRoute: typeof AuthenticatedMoradorHomeRoute
  AuthenticatedMoradorPerfilRoute: typeof AuthenticatedMoradorPerfilRoute
  AuthenticatedMoradorReservarRoute: typeof AuthenticatedMoradorReservarRoute
  AuthenticatedMoradorReservasRoute: typeof AuthenticatedMoradorReservasRoute
}

const AuthenticatedMoradorRouteChildren: AuthenticatedMoradorRouteChildren = {
  AuthenticatedMoradorFilaRoute: AuthenticatedMoradorFilaRoute,
  AuthenticatedMoradorHomeRoute: AuthenticatedMoradorHomeRoute,
  AuthenticatedMoradorPerfilRoute: AuthenticatedMoradorPerfilRoute,
  AuthenticatedMoradorReservarRoute: AuthenticatedMoradorReservarRoute,
  AuthenticatedMoradorReservasRoute: AuthenticatedMoradorReservasRoute,
}

const AuthenticatedMoradorRouteWithChildren =
  AuthenticatedMoradorRoute._addFileChildren(AuthenticatedMoradorRouteChildren)

interface AuthenticatedSindicoRouteChildren {
  AuthenticatedSindicoCarregadoresRoute: typeof AuthenticatedSindicoCarregadoresRoute
  AuthenticatedSindicoComplianceRoute: typeof AuthenticatedSindicoComplianceRoute
  AuthenticatedSindicoConfiguracoesRoute: typeof AuthenticatedSindicoConfiguracoesRoute
  AuthenticatedSindicoDashboardRoute: typeof AuthenticatedSindicoDashboardRoute
  AuthenticatedSindicoEnergiaRoute: typeof AuthenticatedSindicoEnergiaRoute
  AuthenticatedSindicoFinanceiroRoute: typeof AuthenticatedSindicoFinanceiroRoute
  AuthenticatedSindicoMoradoresRoute: typeof AuthenticatedSindicoMoradoresRoute
  AuthenticatedSindicoOnboardingRoute: typeof AuthenticatedSindicoOnboardingRoute
  AuthenticatedSindicoReservasRoute: typeof AuthenticatedSindicoReservasRoute
}

const AuthenticatedSindicoRouteChildren: AuthenticatedSindicoRouteChildren = {
  AuthenticatedSindicoCarregadoresRoute: AuthenticatedSindicoCarregadoresRoute,
  AuthenticatedSindicoComplianceRoute: AuthenticatedSindicoComplianceRoute,
  AuthenticatedSindicoConfiguracoesRoute:
    AuthenticatedSindicoConfiguracoesRoute,
  AuthenticatedSindicoDashboardRoute: AuthenticatedSindicoDashboardRoute,
  AuthenticatedSindicoEnergiaRoute: AuthenticatedSindicoEnergiaRoute,
  AuthenticatedSindicoFinanceiroRoute: AuthenticatedSindicoFinanceiroRoute,
  AuthenticatedSindicoMoradoresRoute: AuthenticatedSindicoMoradoresRoute,
  AuthenticatedSindicoOnboardingRoute: AuthenticatedSindicoOnboardingRoute,
  AuthenticatedSindicoReservasRoute: AuthenticatedSindicoReservasRoute,
}

const AuthenticatedSindicoRouteWithChildren =
  AuthenticatedSindicoRoute._addFileChildren(AuthenticatedSindicoRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMoradorRoute: typeof AuthenticatedMoradorRouteWithChildren
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPendenteRoute: typeof AuthenticatedPendenteRoute
  AuthenticatedSindicoRoute: typeof AuthenticatedSindicoRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMoradorRoute: AuthenticatedMoradorRouteWithChildren,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPendenteRoute: AuthenticatedPendenteRoute,
  AuthenticatedSindicoRoute: AuthenticatedSindicoRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
